language: php
php:
  - '7.2.0'
  - '7.2'
  - '7.3'

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - composer test-ci

after_success:
  - bash <(curl -s https://codecov.io/bash)
